/**
 * Error codes for validation errors.
 */
export enum ValidationErrorCode {
  INVALID_REQUEST_BODY = 'INVALID_REQUEST_BODY',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  MISSING_DB_CREDENTIALS = 'MISSING_DB_CREDENTIALS',
  INVALID_FIELD_FORMAT = 'INVALID_FIELD_FORMAT',
}
