/**
 * Enumeration of broker-related error codes.
 *
 * @category Errors
 * @since 1.0.0
 */
export enum BrokerErrorCode {
  GET_BROKER_FAILED = 'GET_BROKER_FAILED',
  BROKER_STOP_FAILED = 'BROKER_STOP_FAILED',
  BROKER_START_FAILED = 'BROKER_START_FAILED',
  ADD_DBMT_USER_FAILED = 'ADD_DBMT_USER_FAILED',
  UPDATE_DBMT_USER_FAILED = 'UPDATE_DBMT_USER_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNKNOWN = 'UNKNOWN',
}
