/**
 * Enumeration of database-related error codes.
 *
 * @category Errors
 * @since 1.0.0
 */
export enum DatabaseErrorCode {
  GET_START_INFO_FAILED = 'GET_START_INFO_FAILED',
  START_DATABASE_FAILED = 'START_DATABASE_FAILED',
  STOP_DATABASE_FAILED = 'STOP_DATABASE_FAILED',
  RESTART_DATABASE_FAILED = 'RESTART_DATABASE_FAILED',
  LOGIN_DATABASE_FAILED = 'LOGIN_DATABASE_FAILED',
  GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED',
  CREATE_USER_FAILED = 'CREATE_USER_FAILED',
  DELETE_USER_FAILED = 'DELETE_USER_FAILED',
  USER_VERIFY_FAILED = 'USER_VERIFY_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DUPLICATED_DATABASE_PROFILE = 'DUPLICATED_DATABASE_PROFILE',
  NO_SUCH_DATABASE = 'NO_SUCH_DATABASE',
  GET_DB_SPACE_INFO_FAILED = 'GET_DB_SPACE_INFO_FAILED',
  INVALID_VOLUME_STRING = 'INVALID_VOLUME_STRING',
  INVALID_VOLUME_FORMAT = 'INVALID_VOLUME_FORMAT',
  INVALID_VOLUME_INFO = 'INVALID_VOLUME_INFO',
  INVALID_VOLUME_SIZE = 'INVALID_VOLUME_SIZE',
  PARSE_VOLUME_FAILED = 'PARSE_VOLUME_FAILED',
  CONVERT_VOLUME_FAILED = 'CONVERT_VOLUME_FAILED',
  DUPLICATED_FILE = 'DUPLICATED_FILE',
  GET_DBSIZE_FAILED = 'GET_DBSIZE_FAILED',
  COPY_DB_FAILED = 'COPY_DB_FAILED',
  UNKNOWN = 'UNKNOWN',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  OPERATION_IN_PROGRESS = 'OPERATION_IN_PROGRESS',
}
