/**
 * Enumeration of database-related error codes.
 * 
 * 데이터베이스 관련 오류 코드 열거형입니다.
 * 
 * @category Errors
 * @since 1.0.0
 */
export enum DatabaseErrorCode {
    GET_START_INFO_FAILED = 'GET_START_INFO_FAILED',
    START_DATABASE_FAILED = 'START_DATABASE_FAILED',
    STOP_DATABASE_FAILED = 'STOP_DATABASE_FAILED',
    RESTART_DATABASE_FAILED = 'RESTART_DATABASE_FAILED',
    LOGIN_DATABASE_FAILED = 'LOGIN_DATABASE_FAILED',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    DUPLICATED_DATABASE_PROFILE = 'DUPLICATED_DATABASE_PROFILE',
    NO_SUCH_DATABASE = 'NO_SUCH_DATABASE',
    GET_DB_SPACE_INFO_FAILED = 'GET_DB_SPACE_INFO_FAILED',
}

