/**
 * UI labels aligned with CUBRID Manager (Admin) RCP.
 * Source: cubrid-manager .../cubrid/database/Messages.properties, spi/Messages.properties, common/Messages.properties
 */
export const CM = {
  ok: 'OK',
  cancel: 'Cancel',
  close: 'Close',
  refresh: 'Refresh',
  confirm: 'Confirm',
  error: 'Error',
  warning: 'Warning',
  success: 'Success',
  failure: 'Failure',

  loginDatabase: 'Login Database',
  loginDatabaseMsg: 'Log into the selected database.',
  loggingInto: (db) => `Logging into "${db}" database...`,
  connectionSuccessful: 'The connection was successful.',
  userName: 'User name',
  password: 'Password',
  databaseName: 'Database name',
  savePassword: 'Save Password',

  transactionInformation: 'Transaction information',
  activeTransactionsOf: 'Active transactions of database:',
  tranIndex: 'Tran index',
  userNameCol: 'User name',
  host: 'Host',
  processId: 'Process id',
  programName: 'Program name',
  killTransaction: 'Kill transaction',
  killTransactionTitle: 'Kill Transaction',
  killType: 'Kill type',
  killSelectedOnly: 'Kill the selected transaction only',
  killSameUser: 'Kill all transactions associated with the same user',
  killSameHost: 'Kill all transactions associated with the same client host',
  killSameProgram: 'Kill all transactions associated with the same program name',
  killSuccess: 'Transaction has been successfully killed.',

  lockingInformation: 'Locking Information',
  lockSettingClientInfo: 'Lock setting/client information',
  objectLockTable: 'Object lock table',
  lockAndTransaction: 'Lock and Transaction',
  loadingLockAndTransaction: 'Loading lock and transaction information...',
  lockIndex: 'Index',
  pname: 'Pname',
  uid: 'Uid',
  pid: 'Pid',
  isolationLevel: 'Isolation level',
  timeOut: 'Time out',
  oid: 'Oid',
  objectType: 'Object type',
  mode: 'Mode',
  numHolders: 'Num holders',
  numBlockedHolders: 'Num blocked holders',
  numWaiters: 'Num waiters',
  lockEscalation: 'Lock escalation',
  runDeadlockInterval: 'Run deadlock interval',
  currentLockedObjNum: 'Current number of objects which are locked',
  maxLockedObjNum: 'Maximum number of objects which can be locked',

  checkDatabase: 'Check Database',
  checkDatabaseDesc:
    'Verifies a database. If inconsistencies are found, please contact CUBRID Support to help interpret the output and address any indicated problem so that it will not reoccur.',
  repairWhenInconsistency: 'Repair when inconsistency is found',
  jobCompletedSuccess: (job) => `Job ${job} has been completed successfully`,

  createDatabase: 'Create Database',
  deleteDatabase: 'Delete Database',
  deleteDatabaseConfirm: 'Are you sure you want to delete this database?',
  backupDatabase: 'Backup Database',
  restoreDatabase: 'Restore Database',
  compactDatabase: 'Compact Database',
  optimizeDatabase: 'Optimize Database',
  copyDatabase: 'Copy Database',
  renameDatabase: 'Rename Database',
  loadDatabase: 'Load Database',
  unloadDatabase: 'Unload Database',
  dbaConfirm: 'DBA confirm',
  dbaPassword: 'DBA password',

  manageDatabase: 'Manage Database',
  databaseInfo: 'Database Info',
  usedParameterDump: 'Used Parameter Dump',
  planCacheDump: 'Plan Cache Dump',

  manageDatabaseMenu: {
    unload: 'Unload Database...',
    load: 'Load Database...',
    create: 'Create Database...',
    check: 'Check Database',
    compact: 'Compact Database',
    optimize: 'Optimize Database',
    copy: 'Copy Database',
    rename: 'Rename Database',
    restore: 'Restore Database',
    backup: 'Backup Database',
    delete: 'Delete Database',
  },

  // Create Database (createdb wizard)
  createDatabaseMsg: 'Create a new database.',
  createDbJobComplete: (job) => `Job ${job} has been completed.`,
  createDbFailed: 'Failed to start the database. Please verify that the connection credentials are correct.',
  wizardGeneral: 'General Information',
  wizardAdditionalVol: 'Additional Volume Information',
  wizardAutoVol: 'Automatic volume extension',
  wizardSetDbaPass: 'Set DBA Password',
  wizardDbInfo: 'Database Information',
  wizardDbInfoList:
    'You have completed the steps required to create a new database. The new database will be created according to the below preferences.',
  pageSize: 'Page size (byte)',
  logPageSize: 'Log page size (byte)',
  localeCharset: 'Charset',
  userDefined: 'User Defined',
  volumeSize: 'Volume size (Mbyte)',
  genericVolInfo: 'Generic Volume Information',
  genericVolPath: 'Generic volume path',
  logVolInfo: 'Log Volume Information',
  logVolPath: 'Log volume path',
  volumeName: 'Volume name',
  volumePath: 'Volume path',
  volumeType: 'Volume type',
  autoStartDb: 'Auto start database when start the cubrid service',
  passwordConfirm: 'Password Confirm',
  setPassword: 'Set Password',
  readyToCreate: 'Ready to create',
  back: 'Back',
  next: 'Next',
  finish: 'Finish',

  // Unload Database (unloaddb)
  unloadDatabaseMsg: 'Unload the selected database.',
  unloadSuccess: 'The database have been unloaded successfully.',
  unloadResultTitle: 'Unload Database Result',
  unloadResultMsg: 'Below you can view the unload database result informaton.',
  grpDbInfo: 'Database Information',
  targetDbName: 'Target database name',
  targetDirectory: 'Target directory',
  unloadTarget: 'Unload Target',
  unloadOption: 'Unload Option',
  schema: 'Schema',
  data: 'Data',
  all: 'All',
  selectedTables: 'Selected tables',
  notInclude: 'Not include',
  useDelimitedIdentifier: 'Use delimited identifier ("")',
  includeReferencedTables: 'Include referenced tables',
  prefixOutputFiles: 'Prefix for output files',
  fileForHash: 'File for hash',
  numCachedPages: 'Number of cached pages',
  estimatedInstances: 'Estimated number of instances',
  loFileCountPerDir: 'Lo file count per a directory',
  availableClasses: 'Available Classes',

  // Load Database (loaddb)
  loadDatabaseMsg: 'Load the selected database.',
  loadResultTitle: 'Load Database Result',
  loadResultMsg: 'Below you can view the load database result information.',
  unloadedFiles: 'Unloaded Files',
  loadType: 'Load Type',
  path: 'Path',
  date: 'Date',
  selectFromList: 'Select unloaded file from list',
  selectFromRemote: 'Select unloaded file from remote system',
  selectFromLocal: 'Select unloaded file from local system',
  loadOption: 'Load Option',
  loadSchema: 'Load schema',
  loadObject: 'Load object',
  loadIndex: 'Load index',
  loadTrigger: 'Load trigger',
  checkSyntaxAndLoad: 'Check syntax and load database',
  insertionCountPeriodicCommit: 'Insertion count for periodic commit',
  dontUseOid: "Don't use OID",
  dontUpdateStatistics: "Don't update statistics",
  usingErrorControlFile: 'Using error control file',
  ignoredTableFile: 'Ignored table file',
  loadDbTask: 'Load Database',
};
