/**
 * Enumeration of user-related error codes.
 *
 * 사용자 관련 오류 코드 열거형입니다.
 *
 * @category Errors
 * @since 1.0.0
 */
export enum UserErrorCode {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    DATA_SAVE_FAILED = 'DATA_SAVE_FAILED',
    DATA_LOAD_FAILED = 'DATA_LOAD_FAILED',
    DATA_DELETE_FAILED = 'DATA_DELETE_FAILED',
    DATA_UPDATE_FAILED = 'DATA_UPDATE_FAILED',
    RESOURCE_LOCKED = 'RESOURCE_LOCKED',
    LOCK_OPERATION_FAILED = 'LOCK_OPERATION_FAILED',
    OLD_PASSWORD_MISMATCH = 'OLD_PASSWORD_MISMATCH',
    BAD_NEW_PASSWORD = 'BAD_NEW_PASSWORD',
    UNKNOWN = 'UNKNOWN',
}
